### ISSUE TITLE
libplacebo is broken on the latest git master build (2024-10-07-git-496b8d7a13)

### ISSUE THREAD

**Issue by clementiae** [GyanD/codexffmpeg#156] opened 2024-10-09 21:18 UTC
Can't encode vp9 webm with `libplacebo` anymore. Getting the following error:
```
[libplacebo @ 000001f7553ed940] Missing device feature: hostQueryReset
[libplacebo @ 000001f7553ed940] Imported Vulkan device was not created with all required features!
[libplacebo @ 000001f7553ed940] Failed importing vulkan device
[libplacebo @ 000001f7553ed940] Failed importing Vulkan device!
[Parsed_libplacebo_1 @ 000001f74352e600] Query format failed for 'Parsed_libplacebo_1': Generic error in an external library
[fc#0 @ 000001f74352cd00] Error reinitializing filters!
[fc#0 @ 000001f74352cd00] Task finished with error code: -542398533 (Generic error in an external library)
[fc#0 @ 000001f74352cd00] Terminating thread with return code -542398533 (Generic error in an external library)
[vost#0:0/libvpx-vp9 @ 000001f75360e300] [enc:libvpx-vp9 @ 000001f7538611c0] Could not open encoder before EOF
[vost#0:0/libvpx-vp9 @ 000001f75360e300] Task finished with error code: -22 (Invalid argument)
[vost#0:0/libvpx-vp9 @ 000001f75360e300] Terminating thread with return code -22 (Invalid argument)
[out#0/null @ 000001f74352df80] Nothing was written into output file, because at least one of its streams received no packets.
```

Works properly on `ffmpeg-2024-10-02-git-358fdf3083-full_build`

**Comment by GyanD** [comment] 2024-10-10 10:31
This is due to a [regression](https://trac.ffmpeg.org/ticket/11229). Should be fixed now.

**Closed** 2024-10-25 04:41 UTC
